### ISSUE TITLE
gameTitle returns corrupted data for some roms, likely crashing the app

### ISSUE THREAD

**Issue by wxdao** [iNDS-Team/iNDS#20] opened 2018-06-19 10:51 UTC
The app crashed on startup after importing a Pokemon Black 2 rom. After some debugging I managed to identify the cause:

game.gameTitle returned corrupted data instead of real game title. I'm not familiar with the rom parsing code, thus I can't dig further.

<img width="853" alt="qq20180619-175444 2x" src="https://user-images.githubusercontent.com/1405249/41591491-72d8f6fa-73ec-11e8-8424-09b3efff54d8.png">

However, the exact code that raised unhandled index out of bound exception, crashing the app, is located here. I guess it's a typo? It should be >, not >=.

<img width="633" alt="qq20180619-175538 2x" src="https://user-images.githubusercontent.com/1405249/41591694-0b4fe38a-73ed-11e8-96fb-83993babd6a4.png">

Just filed #19 to fix the crash only, and I suggest someone to look into desmume code to solve the title parsing problem.

**Comment by FrederickGeek8** [comment] 2018-06-19 12:29
Hey @wxdao! Do you mind if I drop into a [private chat with you on Gitter](https://gitter.im/)? I would like to figure out what specific ROM you are using because it seems to be a pretty isolated issue right now, and although I would like to keep issue discussions on Github, this is a matter that needs to be discussed privately.

**Comment by FrederickGeek8** [comment] 2018-06-20 00:55
Cannot reproduce with the Pokemon ROM provided by the user. I am reaching out in PM to further diagnose.

**Comment by wxdao** [comment] 2018-06-20 06:40
It's clear now: When the system language is Chinese, iNDS will look for Chinese title in the ROM, while most ROMs don't come with Chinese. And a mistake inside iNDSROMTableViewController.m will crash the app on such corrupted title data for unhandled out of bound exception.

@FrederickGeek8 I've updated PR #19 to solve the problem.

**Comment by FrederickGeek8** [comment] 2018-06-20 18:28
I think your analysis is correct, I will look at your code soon and hopefully merge the pull request!

**Comment by FrederickGeek8** [comment] 2018-06-20 21:48
Closed by #19

**Closed by FrederickGeek8** 2018-06-20 21:48 UTC
Labels: bug
