### ISSUE TITLE
INDS not working 

### ISSUE THREAD

**Issue by vflavored** [iNDS-Team/iNDS#157] opened 2020-02-01 19:20 UTC
Hi, been playing Pokémon soul silver for a couple days and everything was good (except the sprites becoming black squares sometimes ) but now suddenly the app doesn’t open anymore and when I try to do it it takes me back to the home screen. I literally don’t know what to do since the certificate is authorized and it worked till couple hours ago. Please help me to solve this I don’t wanna lose all the progresses and saves, plus I don’t know where they are actually saved . Thank you a lot .

**Comment by vflavored** [comment] 2020-02-01 19:20
Downloaded the app from IEmulators and my phone is an iPhone XR with the lastest version of iOS.

**Comment by inzenette** [comment] 2020-02-04 01:05
the latest version of ios broke all third party apps like iNDS, Cercube, and spotify premium. app developers have to fix their apps themselves to have them work on 13.3, it’s just a matter of time before it’s fixed

**Comment by FrederickGeek8** [comment] 2020-02-09 20:10
@inzenette is this something I have to fix, or the distributors have to fix?

**Comment by inzenette** [comment] 2020-02-09 20:21
@FrederickGeek8 i’m not entirely sure. the delta emulator had to be made a more complex app by the creator, while spotify fix may have been fixed by appvalley, or by the creator. from reading some tweets from operationidroid, he says it’s only caused by the revokes. the distributors will have to fix it, but don’t quote me on that. if it doesn’t fix when the app is signed, then it might you that have to fix it.

**Comment by FrederickGeek8** [comment] 2020-02-09 20:24
I've just opened iNDS on my iPhone which I believe was built before upgrading and it appears to work. I believe that this is an issue with distributors and you should contact them if it's still not working. If they say it's not their issue, please feel free to come back here.

**Closed by FrederickGeek8** 2020-02-09 20:24 UTC
