### ISSUE TITLE
Unable to select R button for repositioning in Edit Profile Layout mode

### ISSUE THREAD

**Issue by mvgian** [iNDS-Team/iNDS#153] opened 2020-01-20 07:50 UTC
**Describe the bug**
Unable to select the R button in Landscape mode while in Edit Profile Layout mode

**To Reproduce**
1. Go to Settings
2: Go to Layout Settings and select Edit Profile Layout
3. Rotate the phone to landscape mode

**Expected behavior**
Able to select all buttons for repositioning in Edit Profile Layout mode

**Screenshots**
![IMG_0152](https://user-images.githubusercontent.com/45260299/72707662-e8cdea00-3b9b-11ea-90ec-c8afafdb8093.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.3

**Comment by FrederickGeek8** [comment] 2020-02-09 21:45
Strange bug. I'll look into it.

**Comment by FrederickGeek8** [comment] 2020-02-09 21:46
Does this only occur in the edit layout mode?

**Comment by mvgian** [comment] 2020-02-10 06:58
Yes. Only in Edit Layout mode from iPhone 11

**Comment by FrederickGeek8** [comment] 2020-02-10 18:57
I, unfortunately, don't have an iPhone 11 and I can't reproduce this issue on either my iPhone X or iPad. The simulator doesn't display the controls, so I'll have to try and fix that before I work on this issue.

Just to make sure, are you running iNDS 1.10.6? If not, what version? You can find the version at the bottom of the settings menu.

**Comment by FrederickGeek8** [comment] 2020-02-10 20:41
I was able to reproduce the issue in the simulator. Let's see if I can fix it.

**Comment by FrederickGeek8** [comment] 2020-02-10 22:41
Fixed in 531e9b2dd47c66091e74c5cc0891e911d3bffc5e. I will push an update soon, stay tuned.

**Comment by FrederickGeek8** [comment] 2020-02-11 00:21
Version 1.10.7 has been released that addresses this issue: https://github.com/iNDS-Team/iNDS/releases/tag/v1.10.7

**Closed by FrederickGeek8** 2020-02-11 00:21 UTC
Labels: bug

**Comment by kingyem** [comment] 2020-08-31 17:52
I’m having the same bug as above, using the version 1.10.7, only difference is the iOS version number

Describe the bug
Unable to select the R button in Landscape mode while in Edit Profile Layout mode

To Reproduce

Go to Settings
2: Go to Layout Settings and select Edit Profile Layout
Rotate the phone to landscape mode
Expected behavior
Able to select all buttons for repositioning in Edit Profile Layout mode

Screenshot 
![F97C7799-D9FF-434C-809B-006DA0635F35](https://user-images.githubusercontent.com/35198970/91750507-ca31d600-ebf5-11ea-9db4-b89ecbab8860.png)


Smartphone (please complete the following information):

Device: iPhone 11
OS: iOS 13.6.1
