### ISSUE TITLE
Mario & Luigi inside bowser story Bug

### ISSUE THREAD

**Issue by Hochulin** [iNDS-Team/iNDS#108] opened 2019-05-26 15:15 UTC
iOS device : iPhone XR
iOS 12.2
Non jailbroken 
Tweakbox
1.9.1

Game freezes in bowser’s battles

**Comment by FrederickGeek8** [comment] 2019-06-13 07:19
This is a duplicate of #92, so please follow the updates there.

**Closed by FrederickGeek8** 2019-06-13 07:19 UTC
