### ISSUE TITLE
Getting My Saves From Dropbox to iNDS

### ISSUE THREAD

**Issue by BiggieSad** [iNDS-Team/iNDS#126] opened 2019-07-25 19:28 UTC
So I was just opening up my iNDS app and went to my Pokémon Diamond rom when I noticed all my saves were gone. I pressed “Launched Normally” and it took me to the beginning as if I was just starting to play. Giving me the start, picking my character, etc
I was confused but luckily thought ahead to sync my app with Dropbox. I went to Dropbox, went to the file and tried copying it over. It didn’t work. It said this;
![A421A560-02CB-4336-92D0-4A2EBC1FB390](https://user-images.githubusercontent.com/53315338/61902410-dddd1a00-aed6-11e9-9200-79e1ef006ce2.png)

(Mind you all the saves are still .dsv and that dark screen stayed, idk why)
I tried seeing if this was an issue for others but very little solutions came up. There’s solutions for computer, Desume, and some other things. I’m just trying to get my game back, I went through the struggles of restarting over and over when the app was getting revoked so I tried to get around it. Now this happens. Please I need help

I use the app on my iPhone 8 (plus I believe? Can’t exactly remember) 
I got the app from Tweakbox
![1D297B06-0296-4CE4-8FAB-B16A84C6FAA7](https://user-images.githubusercontent.com/53315338/61902737-a0c55780-aed7-11e9-8477-db398815cb01.png)
That’s what the files look like in my Dropbox
I would like to get this solved soon so I am prepared for anything else to come
Thank you

**Comment by BiggieSad** [comment] 2019-07-27 00:01
Oh and I’m on IOS 12.3.1

**Comment by FrederickGeek8** [comment] 2019-07-27 02:49
What is the `.ips` file? That could be the cause of the errors.

**Comment by BiggieSad** [comment] 2019-07-27 03:25
The .ips doc is just my layout saved. The strange thing is it’s the only thing that syncs in whenever I open the app. The actual saves don’t sync in. 
I’m not sure if there’s a certain way to export the saves, all I do is tap the file, press “export”, and since “copy to INDS” is the only option other than “open in iTunes” (which does nothing but either export it to my notes or back on Dropbox) that’s what I choose. I have no idea what I’m doing wrong

**Comment by FrederickGeek8** [comment] 2019-07-27 03:28
Oh, I just reread your issue. Did you try copying the DSV from Dropbox on iOS? The Dropbox sync feature in iNDS settings should take care of everything for you and so you shouldn't need to copy things over. Was there a problem with that?

**Comment by BiggieSad** [comment] 2019-07-27 03:38
Yes I had to try and copy because when I’d go in and the app would say “Syncing started” or however it said it, nothing was synced. Nothing was there still so I thought I had to copy it over

**Comment by FrederickGeek8** [comment] 2019-07-27 03:44
You should wait for the sync to complete or failed. Either "Synced Completed!" or "Failed to sync!" should show.

**Comment by BiggieSad** [comment] 2019-07-27 03:55
It completed the syncing and still nothing. Is there something I should do to try and help it notice the saves? I have the syncing on though sometimes even before I have it on it claims it’s completed. I just have no clue what’s going on

**Comment by FrederickGeek8** [comment] 2019-07-27 04:47
[Message me on Gitter](https://gitter.im/iNDS-Team/iNDS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and we can try and diagnose the problem.

**Comment by BiggieSad** [comment] 2019-07-27 05:09
Alright

**Comment by BiggieSad** [comment] 2019-07-27 05:16
I sent a message, though I don’t know how all this stuff works lol

**Comment by dami93c** [comment] 2019-08-27 13:26
@frederik 

I read in a post from a user who explained to you the problem of saving from dropbox to the Inds emulator?  considering that lately the certificates on ios devices do not last long, in order not to risk to always lose the data (currently I synchronize them on droppbox) how is it possible to transfer them to inds?  Has a solution to that problem been raised?  because as soon as I install iNds again he charges me nothing even having it synchronized with dropbox, so I should always start again.  I await your info

**Comment by FrederickGeek8** [comment] 2019-08-27 13:28
I forgot to update this issue. The problem was that the user transferred the wrong ROM to iNDS.

@dami93c I will message you on Gitter

**Closed by FrederickGeek8** 2019-08-27 13:28 UTC

**Comment by dami93c** [comment] 2019-08-27 13:31
and therefore how is it possible to transfer a rescue to an emulator and resume from there?  I speak specifically of pokemon soul Silver, doing "export" tells me invalid extension
