### ISSUE TITLE
Ace Attorney Games 3D Sections Error With Screenshot, Savestate and ROM (AAI)

### ISSUE THREAD

**Issue by BAKAResh** [iNDS-Team/iNDS#4] opened 2018-05-11 18:14 UTC
REPOST FROM PREVIOUS GITHUB. Original post by AmaidoPro. 

There has been already a couple of people complaining about 3D parts in ace attorney games, the problem is not being able to examine certain objects (on this tape you need to examine the blood), so without further to do, here is all you need to attempt this yourself (Ace Attorney Investigations)

Screenshot: https://user-images.githubusercontent.com/38716199/39230679-4bb91d4c-485f-11e8-9c5d-d7cfbec25bda.png

ROM: https://drive.google.com/open?id=1T4ljKskZegy8EPBzPstm7GTyMmbMPfom

Save State (Auto-Save): https://drive.google.com/open?id=1aRkIo2HdBIaAhvA1-2ZTyPfL8byvjuFu

I would really like to get past this scene in Ace Attorney Investigations. All the above should be enough to check it yourself. I would really appreciate if you could fix this as soon as possible. Thanks for the support iNDS Team!

**Comment by BAKAResh** [comment] 2018-05-12 03:51
Let me get it resaved and reuploaded.

**Comment by AmaidoPro** [comment] 2018-05-13 19:32
Hey I gave you @FrederickGeek8 access to this right now, hope you can work on this issue. (Btw I use a translation to Spanish mod but it has the exact same errors on Japanese and English original versions as well as in all Ace Attorney games with 3D components.)
Good luck figuring this out!

**Comment by syto203** [comment] 2018-05-23 18:48
did you try on PC or Mac with latest version of desmume as it may be a core issue not just for iNDS

**Comment by FrederickGeek8** [comment] 2018-05-23 20:03
I believe there are some issues to be dealt with iNDS. Using a sort of naive replacement of the DeSmuME core in iNDS with DeSmuME 0.9.11, we [get slightly different results in AAI.](https://www.youtube.com/watch?v=qXQvbZD4a0E). I think that I wasn't able to test this on the desktop DeSmuME because I couldn't figure out how to load the file in (or there are some compatibility issues that need to be dealt with – it was a while ago when I was testing this so I forget, I'm sorry)

As for Apollo Justice, I notice that it does work! However, the coordinates are slightly off w.r.t where the pointer is on screen (no video at the moment, sorry). I suspect that this is something to do with type conversion, however, I really don't know. If you want to check it out yourself, I know (or at least I think I remember) that Apollo Justice is utilizing the [`gfx3d_glPosTest ` test in gfx3d.cpp](https://github.com/TASVideos/desmume/blob/release_0_9_11/desmume/src/gfx3d.cpp#L1632). I suppose I could post my nieve integration of DeSmuME 0.9.11 as this issue is honestly going to take more time than I'm willing to commit for a while (without help, that is). I was able to test this on desktop purely based on the fact that the scene in question is at the beginning of the story, and thus much more accessible.

I don't know if @WilliamLCobb was able to have any more success in his endeavors. I might have really screwed up in my implementation of the DeSmuME 0.9.11 core since I basically used it as a drop-in replacement, thus if there are issues specific to iNDS, they would likely remain.

**Comment by AmaidoPro** [comment] 2018-06-04 06:51
Hey @FrederickGeek8 nice thing you figured out the problem! However, I get that if you change the core you may need to adapt everything again so maybe if you could find a workaround it would be great!

**Comment by WilliamLCobb** [comment] 2018-06-04 07:06
I actually added DeSmuME in the iNDS 2.0 branch. Though I can’t imagine what you did is very different than my implementation. From what I saw, a ton of bugs were fixed in the games I played.

The only thing that’s left unfinished in that branch is the UI and where DeSmuME is configured to save files. An OpenGL render implementation for iOS would also be nice and would bring a big performance increase.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cbranch** [comment] 2018-10-05 22:06
Hi, I think I have a solution.

The 3D sections work perfectly for me when running iNDS w/ DeSmuME 0.9.11 in the iOS Simulator, but fail on my iPhone 6S. Since the emulation core is otherwise identical, I strongly suspect the bug is specific to compiling to the arm64 backend.

With a identical save state in one of the buggy games loaded on both phone and simulator, I compared the output of gfx3d_glPosTest on DeSmuMe desktop vs iNDS and the resulting matrix is identical. Yet, on iNDS the test fails (since it moves on to test another object, which the desktop build doesn't do).

Given the graphics operations are correct, the next step is to figure out why this value is not being interpreted correctly. To be quite frank, I have no idea how the DS graphics engine really works, but if it's anything like a typical GPU then the game code needs to load some GPU context into memory, or something similar - anyway, the 3D position registers, and thus gfx3d_glGetPosRes. Positive floats are correctly converted to fixed point, but negative floats on arm64 are *not*. The problem is right here:

`unsigned int gfx3d_glGetPosRes(unsigned int index)
{
	return (unsigned int)(PTcoords[index] * 4096.0f);
}`

This is undefined behaviour per the rules for converting floats to integers, so compiler does whatever it likes - hence the divergent behaviour.

If instead we convert to a signed int (legal per the C standard) before converting to unsigned (also legal per the C standard, and matches the amd64 behaviour of reinterpreting the signed two's complement as an unsigned value):

`unsigned int gfx3d_glGetPosRes(unsigned int index)
{
	return (unsigned int)(PTcoords[index] * 4096.0f);
}`

Then the registers are properly converted and the game works, as far as I can tell.

Since this is a bug in desmume I can't reasonably submit a pull request here, but I've done it upstream here: https://github.com/TASVideos/desmume/pull/201

@FrederickGeek8, since 0.9.11 isn't even merged to master, I'll let you decide what you want to do with this information.

**Comment by FrederickGeek8** [comment] 2018-10-06 19:08
@cbranch Wow! Thank you so much. Your fix appears to work. I had a hunch that it was something to do with type conversion, but I never made the connections you made. I have included your fix in PR #52 (DeSmuME 0.9.11 update).

**Comment by FrederickGeek8** [comment] 2018-10-09 18:13
Great news! The AAI bug is fixed in #52 along with @cbranch's fixes. Once I merge in #52, this issue should be solved & closed.

**Closed** 2018-10-10 03:16 UTC
Labels: ROM Specific, bug, help wanted
