### ISSUE TITLE
It wont read my dsv.

### ISSUE THREAD

**Issue by JensOnGH** [iNDS-Team/iNDS#202] opened 2020-11-28 02:10 UTC
**Describe the bug**
It not reading my dsv sav or anything.

**To Reproduce**
1. Go to iNDS
2. Press on eCDP
3. Press First Option
4. See error First Option Wont Open Because Its Not Reading The dsv.

**Expected behavior**
To let me put the password.

**Screenshots**
![image](https://user-images.githubusercontent.com/75056068/100491806-40a67d00-30ec-11eb-9005-49c6f9740de6.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version iOS: 13.3 iNDS: 1.10.6

**Smartphone (please complete the following information):**
 - Device: Ipad 5th Generation
 - OS: 13.3
 - Browser Safari
 - Version 1.10.6

**Additional context**
It Might Be Reading It As A Autosave

**Comment by blueingsh** [comment] 2020-11-28 02:15
also the eCDP game is in archive.org, its a rare game and the person that got it wanted to dump it so they did. for the person who wants to see this error search up “McDonalds eCDP archive.org” to get the ROM

**Comment by JensOnGH** [comment] 2020-11-28 02:36
https://archive.org/details/mcdonalds-japan-ecdp-rom-training-nintendo-ds-cartridge-dump right here

**Comment by FrederickGeek8** [comment] 2020-11-28 02:45
I'll look into this in a bit. It could be a versioning issue. @blueingsh were you able to get it to work in DeSmuMe or iNDS?

The relevant discussion is on #197.

**Comment by blueingsh** [comment] 2020-11-28 02:49
I got it working on a NDS loader on my DS since I don't have a PC, The save is .sav and I gave the person who opened the issue a converted .dsv file. I played the game on the loader and it worked perfectly, The person who opened the issue is basically saying that if they press the first button it doesn't allow them for some reason. We contacted each other and they sent me a video of it and they clicked the first button but it didn't allow them.
(Video: https://media.discordapp.net/attachments/782059309713326111/782063278687387679/video0.mp4)

**Comment by JensOnGH** [comment] 2020-11-28 03:03
Theres a new way you dont need the sav anymore you can use a exe but you need your emulators ip address so inds ip adress which I dont know

**Comment by JensOnGH** [comment] 2020-11-28 03:07
Its also way easier with the sav file in my opinion

**Comment by blueingsh** [comment] 2020-11-28 03:08
I agree ^

**Comment by FrederickGeek8** [comment] 2021-01-05 11:42
There is a solution! Or, rather, it at least works for me.

There is a subtle difference between DSV and SAV files. A kind user on archive.org was able to convert to a DSV file (that works for me): https://mega.nz/folder/I1B2AToL#ua7qseSEqs6I2JICw5-IuQ

For those weary of download suspicious stuff, I ran a hex diff on the SAV and DSV file and truly the only difference is that difference between the two file formats.
<img width="882" alt="Screen Shot 2021-01-05 at 7 41 17 PM" src="https://user-images.githubusercontent.com/774597/103642378-fdaeb380-4f8d-11eb-94b3-ae0565b73439.png">

**Comment by FrederickGeek8** [comment] 2021-01-05 11:44
Let me know if it doesn't work, but for the time being, I'm closing this issue as fixed.

**Closed by FrederickGeek8** 2021-01-05 11:44 UTC
